lista/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from paginainicio.views import Create_index_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #url(r'^$', views.Index),
    path('', Create_index_view.as_view(), name="index"),
    url(r'login/', include('login.urls')),
    url(r'^movil/', include('movil.urls')),
    url(r'^reporte/', include('reportes.urls')),
    path('user/', include('user.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movil/urls.py
from django.conf.urls import url
from django.urls import path

from movil.views.actividades.views import *
from movil.views.cargo.views import *
from movil.views.categoria.views import *
from movil.views.categoria_equipo.views import *
from movil.views.dashboard.views import DashboardView
from movil.views.empleado.views import *
from movil.views.equipo.views import *
from movil.views.listas.views import TestView
from movil.views.marca.views import *
from movil.views.orden_trabajo.views import *


app_name = 'movil'

urlpatterns = [
    #vistas de categoria
    url(r'^categoria/lista/$', Categori_Lista.as_view(), name="CategoriaList"),
    url(r'^categoria/create/$', CategoriaCreate.as_view(), name="Categoriacreate"),
    url(r'^categoria/form/$', CategoriaFormView.as_view(), name="Categoriaform"),
    path('categoria/edit/<int:pk>/', CategoriaUpdate.as_view(), name="Category_update"),
    path('categoria/delete/<int:pk>/', CategoriaDelete.as_view(), name="Category_delete"),

    #vistas de cargo
    url(r'^cargo/lista/$', Cargo_Lista.as_view(), name="Cargolist"),
    url(r'^cargo/create/$', CargoCreate.as_view(), name="Cargocreate"),
    path('cargo/edit/<int:pk>/', CargoUpdate.as_view(), name="Cargo_update"),

    #Vistas de empleado
    url(r'^empleado/lista/$', Empleado_Lista.as_view(), name="ListaEmpleado"),
    url(r'^empleado/create/$', Empleado_Create.as_view(), name="Crear_Empleado"),
    path('empleado/edit/<int:pk>/', Empleado_Update.as_view(), name="Actualizar_update"),

    #Vistas de categoria de equipo
    url(r'^cat_equipo/lista/$', Categori_Lista_Equipo.as_view(), name="CategoriaListEq"),
    url(r'^cat_equipo/create/$', CategoriaCreateEq.as_view(), name="CategoraCreatet_Eq"),
    path('cat_equipo/edit/<int:pk>/', CategoriaUpdateEq.as_view(), name="Categoriaupdate_Eq"),

    #Vistas de marca
    url(r'^marca/lista/$', Marca_Lista_Equipo.as_view(), name="MarcaListEq"),
    url(r'^marca/create/$', MarcaCreateEq.as_view(), name="MarcaCreate_Eq"),
    path('marca/edit/<int:pk>/', MarcaUpdateEq.as_view(), name="Marcaupdate_Eq"),

    #Vistas de equipo
    url(r'^equipo/lista/$', Lista_Equipo.as_view(), name="Lista_Equipo"),
    url(r'^equipo/create/$', Create_Equipo.as_view(), name="Create_Equipo"),
    path('equipo/edit/<int:pk>/', Update_Equipo.as_view(), name="Update_Equipo"),

    #Vistas de orden de trabajo
    url(r'^orden_trabajo/lista/$', Orden_Lista.as_view(), name="OrdenList"),
    url(r'^orden_trabajo/create/$', OrdenCreate.as_view(), name="OrdenCreate"),
    path('orden_trabajo/edit/<int:pk>/', OrdenUpdate.as_view(), name="update_orden"),

    #parte de horas
    url(r'^actividades/lista/$', Parte_horas_list.as_view(), name="PhorasList"),
    url(r'^actividades/create/$', Parte_horas_create.as_view(), name="ParteCreate"),
    path('actividades/delete/<int:pk>/', Parte_horas_delete.as_view(), name="Partedelete"),
    path('actividades/edit/<int:pk>/', Parte_horas_update.as_view(), name="Parteupdate"),
    path('actividades/imprimir/pdf/<int:pk>/', generarPDF_parte.as_view(), name="Pdfgenerate"),

    #pagina de principal
    url(r'^dashboard/$', DashboardView.as_view(), name="Dashboard"),
    #listados
    url(r'^listas/$', TestView.as_view(), name="test"),
]

user/urls.py
from django.urls import path

from user.views import *

#app_name = 'user'

urlpatterns = [
    path('lista/', User_Lista.as_view(), name="UserList"),
    path('crear/', Crear_Usuario.as_view(), name="UserCreate"),
    path('edit/<int:pk>/', Actualizar_Usuario.as_view(), name="UserUpdate"),
    path('delete/<int:pk>/', Eliminar_Usuario.as_view(), name="UserDelete"),
    path('cambio/grupo/<int:pk>/', CambioGrupoUser.as_view(), name="User_group_change"),
]

lista/models.py
from django.db import models
from  django.conf import settings

class BaseModelo(models.Model):
    usuario_autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='usuario_autor', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    usuario_modificador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='usuario_modificador', null=True, blank=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True

movil/views/listas/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from movil.forms import ListaForm
from movil.models import *


class TestView(TemplateView):
    template_name = 'listaspro.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'buscar_equipo_id':
                data =[]
                for i in Equipo.objects.filter(CaterogiaEq_id=request.POST['id']):
                    data.append({'id': i.id, 'Cod_equipo': i.Cod_equipo})
            elif action =='autocomplete':
                data =[]
                for i in CaterogiaEquipo.objects.filter(Desc_categoria__icontains=request.POST['term'])[0:10]:
                    item = i.toJSON()
                    item['value'] = i.Desc_categoria
                    data.append(item)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Select Aninados | Django'
        context['form'] = ListaForm()
        return context

lista/templates/horizontal/body.html
{% extends 'base.html' %}

{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        {% include 'horizontal/header.html' %}
        <!-- content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido: <small>{{ request.user.username }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

lista/templates/horizontal/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'imagen/logo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Control de actividades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link"><i class="las la-home"></i> Home</a>
                </li>
                <!--menu de mantenimiento-->
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'movil:ParteCreate' %}" class="dropdown-item"><i
                                class="fas fa-truck-loading"></i> Actividades</a></li>
                        <li><a href="{% url 'movil:Cargolist' %}" class="dropdown-item"><i class="fas fa-boxes"></i>
                            Cargos</a></li>
                        <li><a href="{% url 'movil:CategoriaList' %}" class="dropdown-item"><i class="fas fa-users"></i>
                            Categorias</a></li>
                        <li><a href="{% url 'movil:Lista_Equipo' %}" class="dropdown-item"><i class="fas fa-users"></i>
                            Equipos</a></li>
                        <li><a href="{% url 'movil:CategoriaListEq' %}" class="dropdown-item"><i
                                class="fas fa-shopping-cart"></i> Categoria equipos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Conjuntos componentes</a>
                        </li>
                        <li><a href="{% url 'movil:ListaEmpleado' %}" class="dropdown-item"><i
                                class="fas fa-shopping-cart"></i> Empleados</a></li>
                        <li><a href="{% url 'movil:PhorasList' %}" class="dropdown-item"><i
                                class="fas fa-shopping-cart"></i> Lista actividad</a></li>
                        <li><a href="{% url 'movil:OrdenList' %}" class="dropdown-item"><i
                                class="fas fa-shopping-cart"></i> Orden de trabajo</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Utilitarios</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'UserList' %}" class="dropdown-item"><i
                                class="fas fa-truck-loading"></i> Usuarios</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu3" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Reportes</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'Reporte_act' %}" class="dropdown-item"><i
                                class="fas fa-truck-loading"></i> Reporte de actividades</a></li>
                    </ul>
                </li>
                <!--termina menu-->
            </ul>
        </div>
        <!--navbar-->
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            {% if request.user.groups.all %}
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu4" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                    {% if request.user.groups.all.count > 1 %}
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                            style="left: 0px; right: inherit;">
                            {% for g in request.user.groups.all %}
                                {% if g.id != request.session.group.id %}
                                 <li><a href="{% url 'User_group_change' g.id %}" class="dropdown-item">{{ g.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="las la-users-cog"></i>
                    {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Su ultimo acceso fue {{ request.user.last_login }}
                    </span>
                    <div class="dropdown-divider"></div>
                    <span class="dropdown-header" style="font-size: 12px;">{{ request.user.username }}</span>

                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="las la-envelope mr-2"></i> Editar perfil
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="las la-users mr-2"></i> Cambiar password
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'logout' %}" class="dropdown-item">
                        <i class="las la-power-off"></i> Cerrar Sesion
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">Notificaciones</a>

                </div>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="las la-power-off" aria-hidden="true"></i>
                    Cerrar sesión
                </a>
            </li>
        </ul>
        <!-- fin navbar-->
    </div>
</nav>
<!-- /.navbar -->